version: '3'

services:

    app:
        image: renatodiaslima/node
        container_name: app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
        entrypoint: node index.js
        networks: 
            - node-network
        tty: true
        ports: 
            - "3000:3000"
        depends_on: 
            - db

    nginx-node:
        image: renatodiaslima/nginx-node
        container_name: nginx-node
        networks: 
            - node-network
        tty: true
        ports: 
            - "8080:80"
        depends_on: 
            - app

    db:
        image: renatodiaslima/mysql-node
        command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
        container_name: db
        restart: always
        tty: true
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - node-network

networks:
    node-network:
        driver: bridge